name: Listen Issue Event
on:
  issues:
    types: [opened, edited]
jobs:
  log-event:
    runs-on: ubuntu-latest
    steps:
      - name: Output Issue Title
        run: echo "${{ toJSON(github.event.issue.title) }}"
      - name: Output Issue Author
        run: echo "${{ toJSON(github.event.issue.login) }}"
